### PR TITLE
Princess

### PR DESCRIPTION
**Pull request by sevu**
Is the healing anim needed?
Adding the old Lisar portrait?

moving to the heroes folder after the other PR is ready

### CODE REVIEW

**Comment by konecnyjakub** [comment]
As far as I can tell, she does not have healing ability so animation for it is not needed.
Having a portrait is nice, especially for special/hero units and that one fits her sprite, so yes.

**Comment by sevu** [comment]
she's now like the 1.10 princess

**Comment by konecnyjakub** [comment]
Oh, I just noticed that the healing animation is actually used (it is manually trigged by WML in Night of the living dead one time. But otherwise, everything is alright.

**Review by konecnyjakub — CHANGES_REQUESTED** [review]
Oh, I just noticed that the healing animation is actually used (it is manually trigged by WML in Night of the living dead one time. But otherwise, everything is alright.

**Comment by sevu** [comment]
that's not a  big deal

**Comment by konecnyjakub** [comment]
Your response was very quick :) . Nice that you put a comment about it to the animation.

**Review by konecnyjakub — APPROVED** [review]

**Comment by sevu** [comment]
I was just sitting at the PC when I got your mail :)

**Pull request merged**
