### PR TITLE
special poison

### PR DESCRIPTION
**Pull request by sevu**
I found a way to improve the poison ability.

- [ ] For the 1.13 list: the [filter_wml] tag is not needed anymore, in 1.13 statuses can be filtered with standard unit filters

### CODE REVIEW

**Review by konecnyjakub — COMMENTED** [review]
Basing Cursed Ghast on core Ghast and simplifying its animations are, on its own, good things. Using text poisoned from textdomain wesnoth is also nice as is {VARIABLE second_unit.status.poisoned yes}. What I do not like is the new definition of the weapon special. It looks like an ugly hack to me and actually it does not work on both Wesnoth 1.12 and 1.13 (I mean on undead).

**Comment by sevu** [comment]
I tested it too and it worked, maybe you forgot to add the {POISING} event macro to the scenario in which you tested it. In 1.13 you could add it to the [campaign] tag too.

For me it wasn't working in 1.13 before, I think second_unit.status.poisoned on was the reason. (didn't compare with 1.12)

**Comment by sevu** [comment]
Should look better now, I suppose it was the + and the too much talk which looked disturbing.
The ability must use two tags, but I think that's fine
-> [poison] to change the inherited name/description
-> [poison_g] to associate it with the corresponding event.

**Comment by konecnyjakub** [comment]
> maybe you forgot to add the {POISING} event macro to the scenario in which you tested it

Oh, right. Sorry.

**Comment by konecnyjakub** [comment]
Well, it turns out that just this works fine:

> [+poison]
    id=poison_g
    name= _ "cursed poison"
    description= _ "This attack poisons not only the living but also the undead. Poisoned units lose 8 HP every turn until they are cured or are reduced to 1 HP. Poison can not, of itself, kill a unit."
[/poison]

Also, as this weapon special is used by just 1 unit type, we can move its events to definition of the unit type.

**Comment by konecnyjakub** [comment]
But these are just some random ideas. Feel free to ignore them. Also special= in weapon filter checks for special's id, not tag name afaik.

**Review by konecnyjakub — APPROVED** [review]
Looks better now. I am going to merge this.

**Pull request merged**
