### PR TITLE
true -> yes

### PR DESCRIPTION
**Pull request by sevu**
While it's perfectly fine to use true/false instead of yes/no, it's been recently deprecated.

I played part of your campaign, was quite nice ;)

### CODE REVIEW

**Comment by konecnyjakub** [comment]
Oh, yes, I have read recently that one of them was deprecated but I was not sure which one. Thanks for reminding me. I will merge this in the evening after I return home.
On your second sentence, I assume that you are talking about For Power, am I right? If it is the case, thank you. I have started creating more campaigns but only that one is on the add-ons server and this is just a port of someone else's campaign.

**Comment by konecnyjakub** [comment]
Merged, thank you.

**Comment by sevu** [comment]
Oh, no, I meant this one. I don't know the others.

**Comment by konecnyjakub** [comment]
Ok but feel free to try them out. Feedback is always welcome :) . Here on GitHub are For Power and also Sage of James but the latter it is in very early stage of development. Maybe I will also add Towards the Light and The Memories here soon.

**Pull request merged**
