### PR TITLE
changing naming scheme

### PR DESCRIPTION
**Pull request by sevu**
What about this?

### CODE REVIEW

**Comment by konecnyjakub** [comment]
Hmm, or maybe we could drop the prefix for all unit types (even that zz(z)) completly. It is really unusual.

**Comment by sevu** [comment]
Would be fine too. Prefix or not, anything is better than the sequential listing.

**Comment by konecnyjakub** [comment]
I cannot see which purpose does that prefix serve and actually most add-ons do not use it. So I would remove it altogether.

**Comment by sevu** [comment]
If you have many unit lines or look at an unknown faction it's quite helpful. Like in ageless.
But here it doesn't matter much.

**Comment by konecnyjakub** [comment]
Well, Ageless is Ageless :P. For many lines, one can always organize them in sub-folders. In our case, after the cleanups, we do not have so many unit types.

**Comment by sevu** [comment]
Changing the Scheme would resulting conflicts with the other PR, I think it's best to do this later.

**Comment by konecnyjakub** [comment]
Nah, git is smart when you rename files. And if it fails to recognize the files, you can always do rebase.

**Comment by sevu** [comment]
If it's like that... there's a new branch.

**Comment by konecnyjakub** [comment]
Cherry-picked as 920423ac.

**Comment by konecnyjakub** [comment]
Well, GitHub reports merge conflicts but rebase went just fine.

**Pull request closed without merging**
