### PR TITLE
Wesnoth 1.13 updates

### LINKED ISSUE #3: Updates for Wesnoth 1.13
I will use this to keep track of things that should be updated for Wesnoth 1.13 once I drop support for 1.12.

- [x] use macro ABILITY_LEADERSHIP instead of ABILITY_LEADERSHIP_LEVEL_X
- [x] add special note SPECIAL_NOTES_DEFENSE_CAP for cavalry units
- [x] use [message] image=none instead of magical comment for wmllint
- [x] remove {MAGENTA_IS_THE_TEAM_COLOR}, {SOUND:SLOW} and {SOUND:POISON}
- [x] undead_variation=wolf for the hound

### PR DESCRIPTION
**Pull request by konecnyjakub**
This closes #3.

### CODE REVIEW

**Comment by konecnyjakub** [comment]
As Wesnoth 1.14 will be announced tomorrow and no patches for 1.12 are planned, the only blocker for merging is missing wolf variation for custom zombies.

**Comment by konecnyjakub** [comment]
I removed the commit with wolf undead variant for Hound. It is a really small change so it can be done later (when we actually have wolf variation for higher level zombies).

**Comment by sevu** [comment]
I saw the forum thread ans thought this would be a bit better.
I could not see the animation and rule out if the engine shows for a moment the lvl 1 mounted variation – pre/post advancement events could be an alternative.

This change has the side effect, that once an wolf variation is added, existing units won't magically switch to it. (currently the varriation=wolf is still stored, just not having an effect)

**Comment by konecnyjakub** [comment]
Hmm, maybe it would be better to add wolf variation with sprites from soulless wolf. They should be used anyway, just with a bit different colors.

**Comment by sevu** [comment]
Hmm that reminds me of... There exists this https://wiki.wesnoth.org/ImagePathFunctionWML#CS:_Color-shift_function
One scenario in UtBS uses colorshifting for human unit sprites, I forgot which one. Not sure if they used ~CS or ~PAL. That would open new possibilities, such as applying it as well on the drake and gryphon sprites, using adjustments for the heroes, having no need for a separate set of level L2,3,4 images, or if, the -r option of the wesnoth executable can be used to create image files with the Image Path Functions applied.
The question is what values to choose, and if they can be retrieved by comparing a pixel of the level 1 image with the higher level ones.

**Comment by konecnyjakub** [comment]
Ah, yes, image paths functions might help with this. Having no images on disc would be nice.
Well, I took a look on how is it done in UtBS and it actually uses CHAN (which was added in 1.13): https://github.com/wesnoth/wesnoth/blob/master/data/campaigns/Under_the_Burning_Suns/utils/macros.cfg#L101.

**Pull request merged**
